name: Test

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  llvm-mingw:
    name: LLVM MinGW
    runs-on: windows-11-arm

    defaults:
      run: { shell: pwsh }

    steps:
      - uses: actions/checkout@v6

      - name: Download LLVM MinGW
        run: >-
             curl.exe -LO "https://github.com/mstorsjo/llvm-mingw/releases/download/20251202/llvm-mingw-20251202-ucrt-aarch64.zip" &&
             unzip llvm-mingw-20251202-ucrt-aarch64.zip &&
             cvpa llvm-mingw-20251202-ucrt-aarch64/bin | tee -a "${env:GITHUB_PATH}"

      - name: Run x86-32 EXE
        run: |
             clang++ --target=i686-w64-mingw32 -static test.cpp -o test.exe
             .\test.exe

      - name: Run x86-64 EXE
        run: |
             clang++ --target=x86_64-w64-mingw32 -static test.cpp -o test.exe
             .\test.exe

      - name: Run ARM64 EXE
        run: |
             clang++ --target=aarch64-w64-mingw32 -static test.cpp -o test.exe
             .\test.exe

      - name: Run ARM64EC EXE
        run: |
             clang++ --target=arm64ec-w64-mingw32 -static test.cpp -o test.exe
             .\test.exe

  llvm-msvc:
    name: LLVM MSVC
    runs-on: windows-11-arm

    defaults:
      run: { shell: pwsh }

    steps:
      - uses: actions/checkout@v6

      - name: Add LLVM into PATH
        run: >-
             echo "C:\Program Files\LLVM\bin" | tee -a "${env:GITHUB_PATH}"

      - name: Run x86-32 EXE
        run: |
             clang++ --target=i686-pc-windows-msvc -static test.cpp -o test.exe
             .\test.exe

      - name: Run x86-64 EXE
        run: |
             clang++ --target=x86_64-pc-windows-msvc -static test.cpp -o test.exe
             .\test.exe

      - name: Run ARM64 EXE
        run: |
             clang++ --target=aarch64-pc-windows-msvc -static test.cpp -o test.exe
             .\test.exe

      - name: Run ARM64EC EXE
        run: |
             clang++ --target=arm64ec-pc-windows-msvc -static -lsoftintrin test.cpp -o test.exe
             .\test.exe
