name: Test

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  ubuntu-arm64:
    name: Ubuntu ARM64
    runs-on: ubuntu-26.04-arm

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: >-
             sudo apt-get update ;
             sudo apt-get purge mono-runtime ;
             sudo apt-get install -y --no-install-recommends
             wine wine-binfmt

      - name: Download LLVM MinGW
        run: >-
             wget 'https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64.tar.xz' &&
             tar -xaf llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64.tar.xz &&
             readlink -fe llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64/bin | tee -a "${GITHUB_PATH}"

      - name: Run ARM64 EXE
        run: |
             aarch64-w64-mingw32-clang -Wall -Wextra test.c -o test.exe
             ./test.exe
